name: 'Terraform'
permissions:
  id-token: write
  contents: read
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs: 
  deploy-infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    environment: prd
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # 1Checkout the repository to the GitHub Actions runner

    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./Terraform"
 
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./Terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./Terraform"
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./Terraform"
